name: Integration Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        integration:
          - content-resolution
          - parcel
          - postcss-cli
          - rollup
          - rollup-sass
          - tailwindcss-cli
          - vite
          - webpack-4
          - webpack-5
        node-version: [16]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      # Cargo already skips downloading dependencies if they already exist
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./oxide/**/Cargo.lock') }}

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npx turbo run oxide:build --filter=//

      - name: Test ${{ matrix.integration }}
        run: npx turbo run test --filter=./integrations/${{ matrix.integration }}
