name: Release Insiders

on:
  push:
    branches: [master]

permissions:
  contents: read

env:
  CI: true
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      # Cargo already skips downloading dependencies if they already exist
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('./oxide/**/Cargo.lock') }}

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npx turbo run oxide:build --filter=//

      - name: Test
        run: npx turbo run test --filter=//

      # This will swap out the Rust-based oxide version with a simple shim. So that you don't
      # require all the Rust specific version at tjkhis time.
      - name: Setup `@tailwindcss/oxide` shim
        run: |
          sed "s#\"@tailwindcss/oxide\": \".*\"#\"@tailwindcss/oxide\": \"file:./oxide-node-api-shim\"#" package.json > package_updated.json
          mv package_updated.json package.json

      - name: Resolve version
        id: vars
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: 'Version based on commit: 0.0.0-insiders.${{ env.SHA_SHORT }}'
        run: npm version 0.0.0-insiders.${{ env.SHA_SHORT }} --force --no-git-tag-version

      - name: Publish
        run: npm publish --tag insiders
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Trigger Tailwind Play update
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TAILWIND_PLAY_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'tailwindlabs',
              repo: 'play.tailwindcss.com',
              ref: 'master',
              workflow_id: 'upgrade-tailwindcss.yml',
              inputs: {
                insidersVersion: '0.0.0-insiders.${{ env.SHA_SHORT }}'
              }
            })
